### ISSUE TITLE
Release and freezing ML-KEM API?

### ISSUE THREAD

**Issue by tomato42** [GiacomoPope/kyber-py#86]
Hey, could we create a new version and push to pypi?
And at the same time, freeze the ML-KEM API?

I'm asking as I have integrated kyber-py into tlslite-ng: https://github.com/tlsfuzzer/tlslite-ng/pull/530 but I'm just using current `main` for testing, would be nicer if I could use pypi package instead...

**Comment by GiacomoPope** [comment]
somewhat annoyingly someone else uploaded my (old) code to pypi: https://pypi.org/project/kyber-py/ which confuses things a little. As for the API, some people may want to allow using the seeds in various ways rather than the private key itself, which there could be better API for, but I don't know if any of the existing functions will need to change?

**Comment by tomato42** [comment]
I wonder if you can't complain about squatting...

for the API: as the public API I consider basically just the existence of the ML_KEM_512, ML_KEM_768, ML_KEM_1024 objects and then the fact that they have the `keygen()`, `encaps()`, and `decaps()` with the static order and types of inputs/outputs. How the private keys can be serialised and deserialised is secondary, and it can always be handled by adding a `keygen_from_seed` method

**Comment by GiacomoPope** [comment]
OK, then I'm happy with this concept of freezing. As for pypi, not sure what the best thing to do is, so i'll think about it a bit i guess

**Comment by tomato42** [comment]
even if it's not pushed to pypi, a tagged release would still be nice :)

**Comment by GiacomoPope** [comment]
I have made a version release (https://github.com/GiacomoPope/kyber-py/releases/tag/v1.0) and with your PR #87 I believe this is now closed
